### ISSUE TITLE
Upgrade to newer version of katex

### ISSUE THREAD

**Issue by hhimanshu** [talyssonoc/react-katex#48]
Hey

How can I upgrade react-katex to latest version of katex?
The current version does not support newline syntax `\\` and `\newline`  

Try yourself at https://katex.org/versions.html and you would see something like below  
<img width="1675" alt="screen shot 2018-10-21 at 11 21 07 am" src="https://user-images.githubusercontent.com/6589036/47268814-7d721400-d523-11e8-9589-0f46d979ca02.png">

Please let me know  
Thanks

**Comment by mrm007** [comment]
@MatejBransky "your" project's page doesn't say it's a fork of this project. And you blatantly [slapped your own name](https://github.com/MatejBransky/react-katex/blob/master/package.json#L16-L19) on it and published it as a separate NPM package with your name on it.

Amazing.

**Comment by MatejBransky** [comment]
@mrm007 Technically it's not a real fork because I wrote the source code by myself and repo is coming from my starter pack. So you're right that it's not correct to name it as a "fork". But the readme by itself is a fork so maybe it should contain an information about the fork of readme. Thanks for your notice!
